name = "jkcbikemap"
main = "src/index.ts"
compatibility_date = "2024-05-23"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jkcbikemap_db"
database_id = "9140840a-3ad5-4834-bdbb-fa5dc2a4bf1a"

[[send_email]]
name = "SEND_EMAIL"

[[routes]]
pattern = "jojomap.kcmo.xyz"
custom_domain = true

[[routes]]
pattern = "map.distorted.work"
custom_domain = true

# In case we need durable objects later
# [durable_objects]
# bindings = []

# [[migrations]]
# dir = "./migrations"
